inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 90

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/AbcSize:
  IgnoredMethods:
    - test_display

Naming/MethodParameterName:
  AllowedNames:
    - y

Style/Documentation:
  Exclude:
    - 'test*.rb'

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
