inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/AbcSize:
  IgnoredMethods:
    - test_display

Naming/MethodParameterName:
  AllowedNames:
    - y
    - id

Style/Documentation:
  Exclude:
    - 'test*.rb'

Style/NumericPredicate:
  EnforcedStyle: comparison
